#pragma warning disable SA1028 // Code must not contain trailing whitespace
/*
 * Meetup Management Service API
 *
 * Meetup Management Service API
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
#pragma warning restore SA1028 // Code must not contain trailing whitespace

using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using DotNetRu.MeetupManagement.WebApi.Contract.Attributes;
using DotNetRu.MeetupManagement.WebApi.Contract.Models;

namespace DotNetRu.MeetupManagement.WebApi.Contract.Controllers
#pragma warning disable SA1028 // Code must not contain trailing whitespace
{ 
    /// <inheritdoc />
    /// <summary>
    /// 
    /// </summary>
#pragma warning restore SA1028 // Code must not contain trailing whitespace
#pragma warning disable SA1649
    public abstract class VenueApiController : ControllerBase
#pragma warning restore SA1649
#pragma warning disable SA1028 // Code must not contain trailing whitespace
    { 
        /// <summary>
        /// Create venue draft
        /// </summary>
        
        /// <param name="venueDraft"></param>
        /// <response code="201">Draft was successfully created</response>
        /// <response code="400">Invalid request parameters</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="409">Draft is already exists</response>
        [HttpPost]
        [Route("/venues/draft")]
        [ValidateModelState]
        [SwaggerOperation("CreateVenueDraft")]
        [SwaggerResponse(statusCode: 201, type: typeof(VenueDraft), description: "Draft was successfully created")]
        [SwaggerResponse(statusCode: 400, description: "Invalid request parameters")]
        [SwaggerResponse(statusCode: 401, description: "Unauthorized")]
        [SwaggerResponse(statusCode: 409, description: "Draft is already exists")]
        public abstract ActionResult<VenueDraft> CreateVenueDraft([FromBody]CreateVenueDraftParameters venueDraft);
        
        /// <summary>
        /// Delete venue draft
        /// </summary>
        
        /// <param name="venueId"></param>
        /// <response code="204">Draft was successfully deleted</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="404">Venue not found</response>
        [HttpDelete]
        [Route("/venues/{venueId}/draft")]
        [ValidateModelState]
        [SwaggerOperation("DeleteVenueDraft")]
        [SwaggerResponse(statusCode: 204, description: "Draft was successfully deleted")]
        [SwaggerResponse(statusCode: 401, description: "Unauthorized")]
        [SwaggerResponse(statusCode: 404, description: "Venue not found")]
        public abstract EmptyResult DeleteVenueDraft([FromRoute][Required]string venueId);
        
        /// <summary>
        /// Get venue draft
        /// </summary>
        
        /// <param name="venueId"></param>
        /// <response code="200">OK</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="404">Venue not found</response>
        [HttpGet]
        [Route("/venues/{venueId}/draft")]
        [ValidateModelState]
        [SwaggerOperation("GetVenueDrafts")]
        [SwaggerResponse(statusCode: 200, type: typeof(VenueDraft), description: "OK")]
        [SwaggerResponse(statusCode: 401, description: "Unauthorized")]
        [SwaggerResponse(statusCode: 404, description: "Venue not found")]
        public abstract ActionResult<VenueDraft> GetVenueDrafts([FromRoute][Required]string venueId);
        
        /// <summary>
        /// Update venue draft
        /// </summary>
        
        /// <param name="venueId"></param>
        /// <param name="properties"></param>
        /// <response code="204">Draft was successfully updated</response>
        /// <response code="400">Invalid request parameters</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="404">Venue not found</response>
        [HttpPut]
        [Route("/venues/{venueId}/draft")]
        [ValidateModelState]
        [SwaggerOperation("UpdateVenueDraft")]
        [SwaggerResponse(statusCode: 204, description: "Draft was successfully updated")]
        [SwaggerResponse(statusCode: 400, description: "Invalid request parameters")]
        [SwaggerResponse(statusCode: 401, description: "Unauthorized")]
        [SwaggerResponse(statusCode: 404, description: "Venue not found")]
        public abstract EmptyResult UpdateVenueDraft([FromRoute][Required]string venueId, [FromBody]UpdateVenueDraftParameters properties);
        
        /// <summary>
        /// Get route values for CreateVenueDraft action
        /// </summary>
        protected static object GetCreateVenueDraftRouteValues()
        {
            return new { };
        }

        /// <summary>
        /// Get route values for DeleteVenueDraft action
        /// </summary>
        protected static object GetDeleteVenueDraftRouteValues([FromRoute][Required]string venueId)
        {
            return new { venueId };
        }

        /// <summary>
        /// Get route values for GetVenueDrafts action
        /// </summary>
        protected static object GetGetVenueDraftsRouteValues([FromRoute][Required]string venueId)
        {
            return new { venueId };
        }

        /// <summary>
        /// Get route values for UpdateVenueDraft action
        /// </summary>
        protected static object GetUpdateVenueDraftRouteValues([FromRoute][Required]string venueId)
        {
            return new { venueId };
        }
    }
#pragma warning restore SA1028 // Code must not contain trailing whitespace
}
