/*
 * Meetup Management Service API
 *
 * Meetup Management Service API
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using Microsoft.AspNetCore.Builder;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Serialization;
using Swashbuckle.AspNetCore.Swagger;
using Swashbuckle.AspNetCore.SwaggerGen;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.SwaggerUI;
using DotNetRu.MeetupManagement.WebApi.Contract.Filters;

namespace DotNetRu.MeetupManagement.WebApi.Contract
{
    /// <summary>
    /// Startup
    /// </summary>
    public class Startup
    {
        /// <summary>
        /// Constructor
        /// </summary>
        public Startup()
        {
        }

        /// <summary>
        /// Configure json options
        /// </summary>
        public void ConfigureJsonOptions(MvcJsonOptions options)
        {
            options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
            options.SerializerSettings.Converters.Add(new StringEnumConverter
            {
                CamelCaseText = true
            });
        }

        /// <summary>
        /// Configure swagger generator options
        /// </summary>
#pragma warning disable CA1822 // Mark members as static
        public void ConfigureSwaggerGenOptions(SwaggerGenOptions options)
#pragma warning restore CA1822 // Mark members as static
        {
            options.SwaggerDoc("0.1.0", new Info
            {
                Version = "0.1.0",
                Title = "Meetup Management Service API",
                Description = "Meetup Management Service API (ASP.NET Core 2.0)",
                Contact = new Contact()
                {
                    Name = "DotNetRu Server Contributors",
                    Url = "https://github.com/DotNetRu/Server",
                    Email = ""
                },
                TermsOfService = ""
            });
            options.CustomSchemaIds(type => type.FriendlyId(true));
            options.DescribeAllEnumsAsStrings();

            // Include DataAnnotation attributes on Controller Action parameters as Swagger validation rules (e.g required, pattern, ..)
            // Use [ValidateModelState] on Actions to actually validate it in C# as well!
            options.OperationFilter<GeneratePathParamsValidationFilter>();
        }

        /// <summary>
        /// Configure swagger UI options
        /// </summary>
#pragma warning disable CA1822 // Mark members as static
        public void ConfigureSwaggerUIOptions(SwaggerUIOptions options)
#pragma warning restore CA1822 // Mark members as static
        {
            //TODO: Either use the SwaggerGen generated Swagger contract (generated from C# classes)
            options.SwaggerEndpoint("/swagger/0.1.0/swagger.json", "Meetup Management Service API");

            //TODO: Or alternatively use the original Swagger contract that's included in the static files
            // options.SwaggerEndpoint("/swagger-original.json", "Meetup Management Service API Original");
        }

        /// <summary>
        /// Returns swagger comments generated file name
        /// </summary>
#pragma warning disable CA1822 // Mark members as static
        public string ContractXmlCommentsFileName => "DotNetRu.MeetupManagement.WebApi.Contract.xml";
#pragma warning restore CA1822 // Mark members as static
    }
}
