/*
 * Meetup Management Service API
 *
 * Meetup Management Service API
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace DotNetRu.MeetupManagement.WebApi.Contract.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class UpdateSpeakerDraftParameters : IEquatable<UpdateSpeakerDraftParameters>
    { 
        /// <summary>
        /// Gets or Sets FirstName
        /// </summary>
        [Required]
        [DataMember(Name="FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or Sets LastName
        /// </summary>
        [Required]
        [DataMember(Name="LastName")]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or Sets CompanyName
        /// </summary>
        [DataMember(Name="CompanyName")]
        public string CompanyName { get; set; }

        /// <summary>
        /// Gets or Sets CompanyUrl
        /// </summary>
        [DataMember(Name="CompanyUrl")]
        public string CompanyUrl { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="Description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets BlogsUrl
        /// </summary>
        [DataMember(Name="BlogsUrl")]
        public string BlogsUrl { get; set; }

        /// <summary>
        /// Gets or Sets ContactsUrl
        /// </summary>
        [DataMember(Name="ContactsUrl")]
        public string ContactsUrl { get; set; }

        /// <summary>
        /// Gets or Sets TwitterUrl
        /// </summary>
        [DataMember(Name="TwitterUrl")]
        public string TwitterUrl { get; set; }

        /// <summary>
        /// Gets or Sets HabrUrl
        /// </summary>
        [DataMember(Name="HabrUrl")]
        public string HabrUrl { get; set; }

        /// <summary>
        /// Gets or Sets GitHubUrl
        /// </summary>
        [DataMember(Name="GitHubUrl")]
        public string GitHubUrl { get; set; }

        /// <summary>
        /// Gets or Sets MeetupIds
        /// </summary>
        [DataMember(Name="MeetupIds")]
        public Collection<string> MeetupIds { get; set; }

        /// <summary>
        /// Gets or Sets TalkIds
        /// </summary>
        [DataMember(Name="TalkIds")]
        public Collection<string> TalkIds { get; set; }

        /// <summary>
        /// Gets or Sets VenueIds
        /// </summary>
        [DataMember(Name="VenueIds")]
        public Collection<string> VenueIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateSpeakerDraftParameters {\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  CompanyName: ").Append(CompanyName).Append("\n");
            sb.Append("  CompanyUrl: ").Append(CompanyUrl).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  BlogsUrl: ").Append(BlogsUrl).Append("\n");
            sb.Append("  ContactsUrl: ").Append(ContactsUrl).Append("\n");
            sb.Append("  TwitterUrl: ").Append(TwitterUrl).Append("\n");
            sb.Append("  HabrUrl: ").Append(HabrUrl).Append("\n");
            sb.Append("  GitHubUrl: ").Append(GitHubUrl).Append("\n");
            sb.Append("  MeetupIds: ").Append(MeetupIds).Append("\n");
            sb.Append("  TalkIds: ").Append(TalkIds).Append("\n");
            sb.Append("  VenueIds: ").Append(VenueIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
#pragma warning disable IDE0041 // Use 'is null' check
            if (ReferenceEquals(null, obj)) return false;
#pragma warning restore IDE0041 // Use 'is null' check
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UpdateSpeakerDraftParameters)obj);
        }

        /// <summary>
        /// Returns true if UpdateSpeakerDraftParameters instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdateSpeakerDraftParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateSpeakerDraftParameters other)
        {
#pragma warning disable IDE0041 // Use 'is null' check
            if (ReferenceEquals(null, other)) return false;
#pragma warning restore IDE0041 // Use 'is null' check
            if (ReferenceEquals(this, other)) return true;

#pragma warning disable CA1309 // Use ordinal stringcomparison
#pragma warning disable CA1307 // Specify StringComparison
            return 
                (
                    string.Equals(FirstName, other.FirstName) ||
                    FirstName != null &&
                    FirstName.Equals(other.FirstName)
                ) && 
                (
                    string.Equals(LastName, other.LastName) ||
                    LastName != null &&
                    LastName.Equals(other.LastName)
                ) && 
                (
                    string.Equals(CompanyName, other.CompanyName) ||
                    CompanyName != null &&
                    CompanyName.Equals(other.CompanyName)
                ) && 
                (
                    string.Equals(CompanyUrl, other.CompanyUrl) ||
                    CompanyUrl != null &&
                    CompanyUrl.Equals(other.CompanyUrl)
                ) && 
                (
                    string.Equals(Description, other.Description) ||
                    Description != null &&
                    Description.Equals(other.Description)
                ) && 
                (
                    string.Equals(BlogsUrl, other.BlogsUrl) ||
                    BlogsUrl != null &&
                    BlogsUrl.Equals(other.BlogsUrl)
                ) && 
                (
                    string.Equals(ContactsUrl, other.ContactsUrl) ||
                    ContactsUrl != null &&
                    ContactsUrl.Equals(other.ContactsUrl)
                ) && 
                (
                    string.Equals(TwitterUrl, other.TwitterUrl) ||
                    TwitterUrl != null &&
                    TwitterUrl.Equals(other.TwitterUrl)
                ) && 
                (
                    string.Equals(HabrUrl, other.HabrUrl) ||
                    HabrUrl != null &&
                    HabrUrl.Equals(other.HabrUrl)
                ) && 
                (
                    string.Equals(GitHubUrl, other.GitHubUrl) ||
                    GitHubUrl != null &&
                    GitHubUrl.Equals(other.GitHubUrl)
                ) && 
                (
                    MeetupIds == other.MeetupIds ||
                    MeetupIds != null &&
                    MeetupIds.SequenceEqual(other.MeetupIds)
                ) && 
                (
                    TalkIds == other.TalkIds ||
                    TalkIds != null &&
                    TalkIds.SequenceEqual(other.TalkIds)
                ) && 
                (
                    VenueIds == other.VenueIds ||
                    VenueIds != null &&
                    VenueIds.SequenceEqual(other.VenueIds)
                );
#pragma warning restore CA1307 // Specify StringComparison
#pragma warning restore CA1309 // Use ordinal stringcomparison
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (FirstName != null)
#pragma warning disable CA1307 // Specify StringComparison
                    hashCode = hashCode * 59 + FirstName.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                    if (LastName != null)
#pragma warning disable CA1307 // Specify StringComparison
                    hashCode = hashCode * 59 + LastName.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                    if (CompanyName != null)
#pragma warning disable CA1307 // Specify StringComparison
                    hashCode = hashCode * 59 + CompanyName.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                    if (CompanyUrl != null)
#pragma warning disable CA1307 // Specify StringComparison
                    hashCode = hashCode * 59 + CompanyUrl.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                    if (Description != null)
#pragma warning disable CA1307 // Specify StringComparison
                    hashCode = hashCode * 59 + Description.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                    if (BlogsUrl != null)
#pragma warning disable CA1307 // Specify StringComparison
                    hashCode = hashCode * 59 + BlogsUrl.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                    if (ContactsUrl != null)
#pragma warning disable CA1307 // Specify StringComparison
                    hashCode = hashCode * 59 + ContactsUrl.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                    if (TwitterUrl != null)
#pragma warning disable CA1307 // Specify StringComparison
                    hashCode = hashCode * 59 + TwitterUrl.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                    if (HabrUrl != null)
#pragma warning disable CA1307 // Specify StringComparison
                    hashCode = hashCode * 59 + HabrUrl.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                    if (GitHubUrl != null)
#pragma warning disable CA1307 // Specify StringComparison
                    hashCode = hashCode * 59 + GitHubUrl.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                    if (MeetupIds != null)
#pragma warning disable CA1307 // Specify StringComparison
                    hashCode = hashCode * 59 + MeetupIds.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                    if (TalkIds != null)
#pragma warning disable CA1307 // Specify StringComparison
                    hashCode = hashCode * 59 + TalkIds.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                    if (VenueIds != null)
#pragma warning disable CA1307 // Specify StringComparison
                    hashCode = hashCode * 59 + VenueIds.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UpdateSpeakerDraftParameters left, UpdateSpeakerDraftParameters right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UpdateSpeakerDraftParameters left, UpdateSpeakerDraftParameters right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
