/*
 * Meetup Management Service API
 *
 * Meetup Management Service API
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace DotNetRu.MeetupManagement.WebApi.Contract.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class UpdatableVenueDraftProperties : IEquatable<UpdatableVenueDraftProperties>
    { 
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [Required]
        [DataMember(Name="Name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [DataMember(Name="Address")]
        public string Address { get; set; }

        /// <summary>
        /// Gets or Sets MapUrl
        /// </summary>
        [DataMember(Name="MapUrl")]
        public string MapUrl { get; set; }

        /// <summary>
        /// Gets or Sets MeetupIds
        /// </summary>
        [DataMember(Name="MeetupIds")]
        public Collection<string> MeetupIds { get; set; }

        /// <summary>
        /// Gets or Sets SpeakerIds
        /// </summary>
        [DataMember(Name="SpeakerIds")]
        public Collection<string> SpeakerIds { get; set; }

        /// <summary>
        /// Gets or Sets TalkIds
        /// </summary>
        [DataMember(Name="TalkIds")]
        public Collection<string> TalkIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdatableVenueDraftProperties {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  MapUrl: ").Append(MapUrl).Append("\n");
            sb.Append("  MeetupIds: ").Append(MeetupIds).Append("\n");
            sb.Append("  SpeakerIds: ").Append(SpeakerIds).Append("\n");
            sb.Append("  TalkIds: ").Append(TalkIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UpdatableVenueDraftProperties)obj);
        }

        /// <summary>
        /// Returns true if UpdatableVenueDraftProperties instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdatableVenueDraftProperties to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdatableVenueDraftProperties other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    Address == other.Address ||
                    Address != null &&
                    Address.Equals(other.Address)
                ) && 
                (
                    MapUrl == other.MapUrl ||
                    MapUrl != null &&
                    MapUrl.Equals(other.MapUrl)
                ) && 
                (
                    MeetupIds == other.MeetupIds ||
                    MeetupIds != null &&
                    MeetupIds.SequenceEqual(other.MeetupIds)
                ) && 
                (
                    SpeakerIds == other.SpeakerIds ||
                    SpeakerIds != null &&
                    SpeakerIds.SequenceEqual(other.SpeakerIds)
                ) && 
                (
                    TalkIds == other.TalkIds ||
                    TalkIds != null &&
                    TalkIds.SequenceEqual(other.TalkIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (Address != null)
                    hashCode = hashCode * 59 + Address.GetHashCode();
                    if (MapUrl != null)
                    hashCode = hashCode * 59 + MapUrl.GetHashCode();
                    if (MeetupIds != null)
                    hashCode = hashCode * 59 + MeetupIds.GetHashCode();
                    if (SpeakerIds != null)
                    hashCode = hashCode * 59 + SpeakerIds.GetHashCode();
                    if (TalkIds != null)
                    hashCode = hashCode * 59 + TalkIds.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UpdatableVenueDraftProperties left, UpdatableVenueDraftProperties right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UpdatableVenueDraftProperties left, UpdatableVenueDraftProperties right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
