/*
 * Meetup Management Service API
 *
 * Meetup Management Service API
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

// ReSharper disable RedundantUsingDirective
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace DotNetRu.MeetupManagement.WebApi.Contract.Models
{ 
    /// <inheritdoc />
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class UpdateMeetupDraftParameters : IEquatable<UpdateMeetupDraftParameters>
    { 
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [Required]
        [DataMember(Name="Name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets VenueId
        /// </summary>
        [DataMember(Name="VenueId")]
        public string VenueId { get; set; }

        /// <summary>
        /// Gets or Sets SpeakerIds
        /// </summary>
        [DataMember(Name="SpeakerIds")]
        public Collection<string> SpeakerIds { get; set; }

        /// <summary>
        /// Gets or Sets TalkIds
        /// </summary>
        [DataMember(Name="TalkIds")]
        public Collection<string> TalkIds { get; set; }

        /// <summary>
        /// Gets or Sets FriendIds
        /// </summary>
        [DataMember(Name="FriendIds")]
        public Collection<string> FriendIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateMeetupDraftParameters {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  VenueId: ").Append(VenueId).Append("\n");
            sb.Append("  SpeakerIds: ").Append(SpeakerIds).Append("\n");
            sb.Append("  TalkIds: ").Append(TalkIds).Append("\n");
            sb.Append("  FriendIds: ").Append(FriendIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        // ReSharper disable once UnusedMember.Global
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
#pragma warning disable IDE0041 // Use 'is null' check
            if (ReferenceEquals(null, obj)) return false;
#pragma warning restore IDE0041 // Use 'is null' check
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UpdateMeetupDraftParameters)obj);
        }

        /// <inheritdoc />
        /// <summary>
        /// Returns true if UpdateMeetupDraftParameters instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdateMeetupDraftParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateMeetupDraftParameters other)
        {
#pragma warning disable IDE0041 // Use 'is null' check
            if (ReferenceEquals(null, other)) return false;
#pragma warning restore IDE0041 // Use 'is null' check
            if (ReferenceEquals(this, other)) return true;

#pragma warning disable CA1309 // Use ordinal stringcomparison
#pragma warning disable CA1307 // Specify StringComparison
            return 
                (
                    // ReSharper disable once RedundantNameQualifier
                    string.Equals(Name, other.Name) ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    // ReSharper disable once RedundantNameQualifier
                    string.Equals(VenueId, other.VenueId) ||
                    VenueId != null &&
                    VenueId.Equals(other.VenueId)
                ) && 
                (
                    SpeakerIds == other.SpeakerIds ||
                    SpeakerIds != null &&
                    SpeakerIds.SequenceEqual(other.SpeakerIds)
                ) && 
                (
                    TalkIds == other.TalkIds ||
                    TalkIds != null &&
                    TalkIds.SequenceEqual(other.TalkIds)
                ) && 
                (
                    FriendIds == other.FriendIds ||
                    FriendIds != null &&
                    FriendIds.SequenceEqual(other.FriendIds)
                );
#pragma warning restore CA1307 // Specify StringComparison
#pragma warning restore CA1309 // Use ordinal stringcomparison
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                // ReSharper disable once NonReadonlyMemberInGetHashCode
                    if (Name != null)
#pragma warning disable CA1307 // Specify StringComparison
                    // ReSharper disable once NonReadonlyMemberInGetHashCode
                    hashCode = hashCode * 59 + Name.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                // ReSharper disable once NonReadonlyMemberInGetHashCode
                    if (VenueId != null)
#pragma warning disable CA1307 // Specify StringComparison
                    // ReSharper disable once NonReadonlyMemberInGetHashCode
                    hashCode = hashCode * 59 + VenueId.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                // ReSharper disable once NonReadonlyMemberInGetHashCode
                    if (SpeakerIds != null)
#pragma warning disable CA1307 // Specify StringComparison
                    // ReSharper disable once NonReadonlyMemberInGetHashCode
                    hashCode = hashCode * 59 + SpeakerIds.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                // ReSharper disable once NonReadonlyMemberInGetHashCode
                    if (TalkIds != null)
#pragma warning disable CA1307 // Specify StringComparison
                    // ReSharper disable once NonReadonlyMemberInGetHashCode
                    hashCode = hashCode * 59 + TalkIds.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                // ReSharper disable once NonReadonlyMemberInGetHashCode
                    if (FriendIds != null)
#pragma warning disable CA1307 // Specify StringComparison
                    // ReSharper disable once NonReadonlyMemberInGetHashCode
                    hashCode = hashCode * 59 + FriendIds.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UpdateMeetupDraftParameters left, UpdateMeetupDraftParameters right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UpdateMeetupDraftParameters left, UpdateMeetupDraftParameters right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
