/*
 * Meetup Management Service API
 *
 * Meetup Management Service API
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace DotNetRu.MeetupManagement.WebApi.Contract.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class UpdateTalkDraftParameters : IEquatable<UpdateTalkDraftParameters>
    { 
        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [Required]
        [DataMember(Name="Title")]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="Description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets SlidesUrl
        /// </summary>
        [DataMember(Name="SlidesUrl")]
        public string SlidesUrl { get; set; }

        /// <summary>
        /// Gets or Sets VideoUrl
        /// </summary>
        [DataMember(Name="VideoUrl")]
        public string VideoUrl { get; set; }

        /// <summary>
        /// Gets or Sets MeetupIds
        /// </summary>
        [DataMember(Name="MeetupIds")]
        public Collection<string> MeetupIds { get; set; }

        /// <summary>
        /// Gets or Sets SpeakerIds
        /// </summary>
        [DataMember(Name="SpeakerIds")]
        public Collection<string> SpeakerIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateTalkDraftParameters {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  SlidesUrl: ").Append(SlidesUrl).Append("\n");
            sb.Append("  VideoUrl: ").Append(VideoUrl).Append("\n");
            sb.Append("  MeetupIds: ").Append(MeetupIds).Append("\n");
            sb.Append("  SpeakerIds: ").Append(SpeakerIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
#pragma warning disable IDE0041 // Use 'is null' check
            if (ReferenceEquals(null, obj)) return false;
#pragma warning restore IDE0041 // Use 'is null' check
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UpdateTalkDraftParameters)obj);
        }

        /// <summary>
        /// Returns true if UpdateTalkDraftParameters instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdateTalkDraftParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateTalkDraftParameters other)
        {
#pragma warning disable IDE0041 // Use 'is null' check
            if (ReferenceEquals(null, other)) return false;
#pragma warning restore IDE0041 // Use 'is null' check
            if (ReferenceEquals(this, other)) return true;

#pragma warning disable CA1309 // Use ordinal stringcomparison
#pragma warning disable CA1307 // Specify StringComparison
            return 
                (
                    string.Equals(Title, other.Title) ||
                    Title != null &&
                    Title.Equals(other.Title)
                ) && 
                (
                    string.Equals(Description, other.Description) ||
                    Description != null &&
                    Description.Equals(other.Description)
                ) && 
                (
                    string.Equals(SlidesUrl, other.SlidesUrl) ||
                    SlidesUrl != null &&
                    SlidesUrl.Equals(other.SlidesUrl)
                ) && 
                (
                    string.Equals(VideoUrl, other.VideoUrl) ||
                    VideoUrl != null &&
                    VideoUrl.Equals(other.VideoUrl)
                ) && 
                (
                    MeetupIds == other.MeetupIds ||
                    MeetupIds != null &&
                    MeetupIds.SequenceEqual(other.MeetupIds)
                ) && 
                (
                    SpeakerIds == other.SpeakerIds ||
                    SpeakerIds != null &&
                    SpeakerIds.SequenceEqual(other.SpeakerIds)
                );
#pragma warning restore CA1307 // Specify StringComparison
#pragma warning restore CA1309 // Use ordinal stringcomparison
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Title != null)
#pragma warning disable CA1307 // Specify StringComparison
                    hashCode = hashCode * 59 + Title.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                    if (Description != null)
#pragma warning disable CA1307 // Specify StringComparison
                    hashCode = hashCode * 59 + Description.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                    if (SlidesUrl != null)
#pragma warning disable CA1307 // Specify StringComparison
                    hashCode = hashCode * 59 + SlidesUrl.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                    if (VideoUrl != null)
#pragma warning disable CA1307 // Specify StringComparison
                    hashCode = hashCode * 59 + VideoUrl.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                    if (MeetupIds != null)
#pragma warning disable CA1307 // Specify StringComparison
                    hashCode = hashCode * 59 + MeetupIds.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                    if (SpeakerIds != null)
#pragma warning disable CA1307 // Specify StringComparison
                    hashCode = hashCode * 59 + SpeakerIds.GetHashCode();
#pragma warning restore CA1307 // Specify StringComparison
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UpdateTalkDraftParameters left, UpdateTalkDraftParameters right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UpdateTalkDraftParameters left, UpdateTalkDraftParameters right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
